<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="23">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="490" BACKGROUND="../img/general/noticias/header_noti.jpg"><B> &nbsp;Ficha 
      Personal </B> </TD>
    <TD WIDTH="17"><IMG SRC="../img/general/noticias/header_noti_right.gif" WIDTH="17" HEIGHT="23"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FF7F00" WIDTH="385" VALIGN="top">
      <TABLE width="100%" border="0" cellspacing="3" cellpadding="3">
        <TR> 
          <TD> Defensor central, de trayectoria y renombre internacional, calculador, 
            atinado en las salidas desde su arco, que hace de de la visi&oacute;n 
            y voz de orden su caracter&iacute;stica principal.<BR>
            <BR>
            Es el &quot;Patr&oacute;n&quot; de las dos &aacute;reas, manda cuando 
            defiende -ordena e impone respeto al rival- y acierta en la b&uacute;squeda 
            del cabezazo en ofensiva, torn&aacute;ndose en un hombre muy peligroso 
            en el juego a&eacute;reo, por su alta estatura y sus condiciones f&iacute;sicas. 
            <P>Fecha de Nacimiento: 18 de Junio de 19/71<BR>
              Lugar: Armenia, Colombia<BR>
              Puesto: defensor<BR>
              N&uacute;mero: 2<BR>
              Estatura: 1, 86 m<BR>
              Peso: 87 kg<BR>
              <BR>
              - Debut en Primera: en Deportes Quind&iacute;o en 1988<BR>
              - Debut en Boca: 3 de Septiembre de 1997 contra Cruzeiro 1-0, con 
              gol de Berm&uacute;dez, -Supercopa-) DT: H&eacute;ctor Veira. <BR>
              - Debut en Torneos Nacionales: 14 de Septiembre de 1997 en Boca 
              (contra Newell&acute;s 2-1).</P>
            <P><B>T&iacute;tulos:<BR>
              </B>- Torneo Colombiano con Am&eacute;rica de Cali en 1991.<BR>
              - Torneo Apertura '98 con Boca Juniors.<BR>
              - Torneo Clausura '99 con Boca Juniors.<BR>
              - Copa Libertadores 2000 con Boca Juniors.<BR>
              - Copa Intercontinental 2000 con Boca Juniors.</P>
            </TD>
        </TR>
      </TABLE>
    </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FF7F00" WIDTH="120" VALIGN="top"> 
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD><IMG SRC="../img/clipart/ficha_personal.jpg" WIDTH="120" HEIGHT="280"></TD>
        </TR>
      </TABLE>
      <? include "menu1.inc"; ?> </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#FFFFFF">
  <TR> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>