<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="23">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="490" BACKGROUND="../img/general/noticias/header_noti.jpg"><B> &nbsp;M&iacute;s 
      &Iacute;dolos</B> </TD>
    <TD WIDTH="17"><IMG SRC="../img/general/noticias/header_noti_right.gif" WIDTH="17" HEIGHT="23"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FF7F00" WIDTH="385" VALIGN="top">
      <TABLE width="100%" border="0" cellspacing="3" cellpadding="3">
        <TR> 
          <TD> 
            <P>Dice 'El Patr&oacute;n' de Jorge Enrique Berm&uacute;dez (Su Padre): 
              Jug&oacute; en el Deportes Quind&iacute;o, Santa Fe y la Selecci&oacute;n 
              Colombia<BR>
              <BR>
              &quot;Cuando era chico, mi &iacute;dolo era mi &quot;viejo&quot;, 
              que jugaba de defensor, como lo hago yo ahora. Me maravillaba que 
              &eacute;l jugara y su forma de hacerlo me marc&oacute; en mi carrera. 
              Si hoy dicen que yo hablo mucho, tendr&iacute;an que haberlo visto 
              y escuchado a mi padre&quot;. .<BR>
            </P>
            <P><BR>
              Dice 'El Patr&oacute;n' de Franco Baresi -jugador del Milan y la 
              Selecci&oacute;n italiana- y de Frank Rijkaard, -jugador del Ajax 
              de Holanda y del Milan. Integr&oacute; y dirigi&oacute; la Selecci&oacute;n 
              Holandesa.-</P>
            <P>&quot;A medida que fui creciendo en los diferentes equipos, los 
              &iacute;dolos que tuve fueron el italiano Franco Baresi y Frank 
              Rijkaard&quot;.</P>
            <P>&nbsp;</P>
    </TD>
        </TR>
      </TABLE>
    </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FF7F00" WIDTH="120" VALIGN="top"> 
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD><IMG SRC="../img/clipart/se_dice.jpg" WIDTH="120" HEIGHT="280"></TD>
        </TR>
      </TABLE>
      <? include "menu1.inc"; ?> </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#FFFFFF">
  <TR> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>