
<TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR BGCOLOR="#666666"> 
    <TD>&nbsp;</TD>
  </TR>
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD> 
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#000000">
        <TR> 
          <TD colspan="2"><A href="?inc=ficha_personal"><FONT color="#FFFFFF">&nbsp;Ficha 
            Personal</FONT></A></TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD> 
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#000000">
        <TR> 
          <TD colspan="2"><A href="?inc=se_dice"><FONT color="#FFFFFF">&nbsp;Se 
            dice de Mi</FONT></A></TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD> 
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#000000">
        <TR> 
          <TD colspan="2"><A href="?inc=vida"><FONT color="#FFFFFF">&nbsp;Vida 
            Personal</FONT></A></TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD> 
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#000000">
        <TR> 
          <TD colspan="2"><A href="?inc=trayectoria"><FONT color="#FFFFFF">&nbsp;Trayectoria</FONT></A></TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
  <TR> 
    <TD> 
      <TABLE WIDTH="120" BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#000000">
        <TR> 
          <TD colspan="2"><A href="?inc=idolos"><FONT color="#FFFFFF">&nbsp;Mis 
            &Iacute;dolos</FONT></A></TD>
        </TR>
      </TABLE>
    </TD>
  </TR>
  <TR BGCOLOR="#FFFFFF"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
