<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="23">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="490" BACKGROUND="../img/general/noticias/header_noti.jpg"><B> &nbsp;Se 
      Dice de Mi</B> </TD>
    <TD WIDTH="17"><IMG SRC="../img/general/noticias/header_noti_right.gif" WIDTH="17" HEIGHT="23"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FF7F00" WIDTH="385" VALIGN="top">
      <TABLE width="100%" border="0" cellspacing="3" cellpadding="3">
        <TR> 
          <TD>&nbsp; </TD>
        </TR>
      </TABLE>
    </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FF7F00" WIDTH="120" VALIGN="top"> 
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD><IMG SRC="../img/clipart/se_dice.jpg" WIDTH="120" HEIGHT="280"></TD>
        </TR>
      </TABLE>
      <? include "menu1.inc"; ?> </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#FFFFFF">
  <TR> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>