<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="23">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="490" BACKGROUND="../img/general/noticias/header_noti.jpg"><B> &nbsp;Trayectoria</B> 
    </TD>
    <TD WIDTH="17"><IMG SRC="../img/general/noticias/header_noti_right.gif" WIDTH="17" HEIGHT="23"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FF7F00" WIDTH="385" VALIGN="top">
      <TABLE width="100%" border="0" cellspacing="3" cellpadding="3">
        <TR> 
          <TD>
            <P> 1988 al '90: debuta en Primera Divisi&oacute;n del f&uacute;tbol 
              colombiano en Deportes Quind&iacute;o.<BR>
              1991 al '96: Am&eacute;rica de Cali (2 veces campe&oacute;n de Colombia 
              -1991 y 1995- y Subcampe&oacute;n de la Copa Libertadores en 1996 
              &#150;pierde la final con River Plate-). <BR>
              1996 al '97: se consagra subcampe&oacute;n con el Benfica de Portugal 
              y participa de la Copa UEFA.<BR>
              1997: el 3 de septiembre debuta en Boca Juniors y convierte el &uacute;nico 
              gol del partido, que le dio la victoria a su equipo frente a Cruceiro, 
              en la Supercopa. H&eacute;ctor Veira era el director t&eacute;cnico 
              &quot;xeneize&quot; en ese momento.<BR>
              1998: campe&oacute;n del Campeonato Apertura '98.<BR>
              1999: campe&oacute;n del Campeonato Clausura '99.<BR>
              2000: campe&oacute;n de la Copa Libertadores.<BR>
              2000: campe&oacute;n de la Copa Intercontinental.</P>
            <P><BR>
              Participaci&oacute;n en la Selecci&oacute;n de Colombia</P>
            <P>1988: subcampe&oacute;n con la Selecci&oacute;n Sub-19 del Sudamericano 
              Juvenil de Argentina. (DT: Juan Pel&aacute;ez)<BR>
              1989: participa con la Selecci&oacute;n Sub-19 del Mundial Juvenil 
              de Arabia Saudita. (DT: Juan Pel&aacute;ez)<BR>
              1992: subcampe&oacute;n con la Selecci&oacute;n Sub-23 del Preol&iacute;mpico 
              de Paraguay (DT: Hern&aacute;n Dar&iacute;o G&oacute;mez).<BR>
              1992: participa con la Selecci&oacute;n Sub-23 de los Juegos Ol&iacute;mpicos 
              de Barcelona, Espa&ntilde;a. (DT: Hern&aacute;n Dar&iacute;o G&oacute;mez).<BR>
              1995: Gira por Asia y Ocean&iacute;a (DT: Hern&aacute;n Dar&iacute;o 
              G&oacute;mez).<BR>
              1995: debuta en la Selecci&oacute;n Mayor de Colombia (Colombia 
              0 - Corea del Sur 1; DT: Hern&aacute;n Dar&iacute;o G&oacute;mez)<BR>
              1995: alcanza el tercer puesto en la Copa Am&eacute;rica de Uruguay 
              (DT: Hern&aacute;n Dar&iacute;o G&oacute;mez).<BR>
              1997: participa en 18 partidos de las Eliminatorias, clasificatorias 
              al Mundial de Francia '98 (DT: Hern&aacute;n Dar&iacute;o G&oacute;mez).<BR>
              1997: Copa Am&eacute;rica en Bolivia. Colombia queda en el quinto 
              lugar (DT: Hern&aacute;n Dar&iacute;o G&oacute;mez).<BR>
              1998: disputa el Mundial de Francia (DT: Hern&aacute;n Dar&iacute;o 
              G&oacute;mez).<BR>
              1999: alcanza el tercer puesto en la Copa Am&eacute;rica de Paraguay 
              (DT: Luis Garc&iacute;a).<BR>
              2000: participa en 3 partidos de las Eliminatorias clasificatorias 
              para el Mundial Jap&oacute;n-Corea 2002 (DT: Luis Garc&iacute;a).</P>
            </TD>
        </TR>
      </TABLE>
    </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FF7F00" WIDTH="120" VALIGN="top"> 
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD><IMG SRC="../img/clipart/trayectoria.jpg" WIDTH="120" HEIGHT="280"></TD>
        </TR>
      </TABLE>
      <? include "menu1.inc"; ?> </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#FFFFFF">
  <TR> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>