<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0" HEIGHT="23">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD WIDTH="490" BACKGROUND="../img/general/noticias/header_noti.jpg"><B> &nbsp;Mi 
      Vida </B> </TD>
    <TD WIDTH="17"><IMG SRC="../img/general/noticias/header_noti_right.gif" WIDTH="17" HEIGHT="23"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FF7F00" WIDTH="385" VALIGN="top">
      <TABLE width="100%" border="0" cellspacing="3" cellpadding="3">
        <TR> 
          <TD width="380">Jorge Hern&aacute;n Berm&uacute;dez Morales naci&oacute; 
            en las postrimer&iacute;as del caluroso verano colombiano de 1971, 
            cerca de las cafetales tierras de Armenia.<BR>
            <BR>
            Hijo de &quot;Carmencita&quot; Morales de Berm&uacute;dez y de Jorge 
            Enrique Berm&uacute;dez, creci&oacute; junto a su hermano Octavio 
            Enrique, jugando entre pl&aacute;tanos, caf&eacute; y yuca, y desparramando 
            su f&iacute;sico por cuanto deporte comenzaba a descubrir.<BR>
            En ese af&aacute;n de descubrir y crecer, recibi&oacute; una nueva 
            compa&ntilde;&iacute;a en sus primeros 12 a&ntilde;os de vida: Vanesa, 
            hermana menor y ni&ntilde;a mimada de la familia Berm&uacute;dez, 
            en medio de un hogar que a&uacute;n permanece arraigado en la tibieza 
            de los 20 grados de temperatura de su finca en Armenia.<BR>
            <BR>
            La pelota comenz&oacute; a cruzarse en su camino desde muy peque&ntilde;o, 
            y fue en Deportes Quind&iacute;o-&quot;en mi equipo&quot;, como suele 
            denominarlo- donde visti&oacute; su primer camiseta.<BR>
            De all&iacute; en m&aacute;s, comenz&oacute; a transitar una carrera 
            deportiva con las vicisitudes que la vida le depara a aquellos que 
            est&aacute;n destinados a ser exitosos en su profesi&oacute;n.<BR>
            <BR>
            Durante su infancia conoci&oacute; a Claudia Patricia B&eacute;rgano, 
            una elegante jovencita colombiana, con quien contrajo enlace en el 
            Valle de Cali, a los 22 a&ntilde;os.<BR>
            Fruto de esta uni&oacute;n naci&oacute; el primero de sus tres hijos, 
            Jorge David, en Colombia, a quien le sigui&oacute; Hern&aacute;n Emmanuel; 
            ambos -fan&aacute;ticos de su padre y de los juegos electr&oacute;nicos- 
            lo acompa&ntilde;an de la mano en varias oportunidades, cuando el 
            equipo &quot;xeneize&quot; ingresa al campo de juego.<BR>
            Joan Sebasti&aacute;n, el m&aacute;s peque&ntilde;o lleg&oacute; con 
            la Libertadores bajo el brazo, el 8 de junio de 2000.</TD>
        </TR>
      </TABLE>
    </TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD BGCOLOR="#FF7F00" WIDTH="120" VALIGN="top"> 
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR> 
          <TD><IMG SRC="../img/clipart/ficha_personal.jpg" WIDTH="120" HEIGHT="280"></TD>
        </TR>
</TABLE>

      <? 
			include "menu1.inc";
	  ?>

</TD>
    <TD BGCOLOR="#FFFFFF" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="508" BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#FFFFFF">
  <TR> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>