
<SCRIPT LANGUAGE="JavaScript">
<!--
function MM_swapImgRestore() { //v3.0
  var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}

function MM_preloadImages() { //v3.0
  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
    if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
}

function MM_findObj(n, d) { //v3.0
  var p,i,x;  if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document); return x;
}

function MM_swapImage() { //v3.0
  var i,j=0,x,a=MM_swapImage.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
   if ((x=MM_findObj(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</SCRIPT>


<BODY BGCOLOR="#FFFFFF" onLoad="MM_preloadImages('../img/downloads/walls/wallpapers_1c.jpg','../img/downloads/walls/wallpapers_2c.jpg','../img/downloads/walls/wallpapers_3c.jpg','../img/downloads/walls/wallpapers_4c.jpg')">
<TABLE WIDTH="665" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR ALIGN="CENTER"> 
    <TD><A HREF="javascript:openwin('wallpapers_ow.html?wall=wallpapers_1l','wallpapers','width=300,height=250,scrollbars=0')" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image1','','../img/downloads/walls/wallpapers_1c.jpg',1)"><IMG NAME="Image1" BORDER="0" SRC="../img/downloads/walls/wallpapers_1b.jpg" WIDTH="150" HEIGHT="100"></A></TD>
    <TD><A HREF="javascript:openwin('wallpapers_ow.html?wall=wallpapers_2l','wallpapers','width=300,height=250,scrollbars=0')" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image2','','../img/downloads/walls/wallpapers_2c.jpg',1)"><IMG NAME="Image2" BORDER="0" SRC="../img/downloads/walls/wallpapers_2b.jpg" WIDTH="150" HEIGHT="100"></A></TD>
    <TD><A HREF="javascript:openwin('wallpapers_ow.html?wall=wallpapers_3l','wallpapers','width=300,height=250,scrollbars=0')" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image3','','../img/downloads/walls/wallpapers_3c.jpg',1)"><IMG NAME="Image3" BORDER="0" SRC="../img/downloads/walls/wallpapers_3b.jpg" WIDTH="150" HEIGHT="100"></A></TD>
    <TD><A HREF="javascript:openwin('wallpapers_ow.html?wall=wallpapers_4l','wallpapers','width=300,height=250,scrollbars=0')" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image4','','../img/downloads/walls/wallpapers_4c.jpg',1)"><IMG NAME="Image4" BORDER="0" SRC="../img/downloads/walls/wallpapers_4b.jpg" WIDTH="150" HEIGHT="100"></A></TD>
  </TR>
</TABLE>
</BODY>

