<HTML>
<HEAD>
<TITLE>Resultado Encuesta</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<LINK REL="stylesheet" HREF="../include/estilos.css">
</HEAD>
<BODY LEFTMARGIN="3" TOPMARGIN="3" MARGINWIDTH="3" MARGINHEIGHT="3" BGCOLOR="#FF7F00">
<TABLE WIDTH="300" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#000000" ALIGN="CENTER"> 
    <TD>Resultados de la Encuesta</TD>
  </TR>
  <TR BGCOLOR="#FF7F00" ALIGN="CENTER"> 
    <TD><IMG SRC="../img/general/spacer.gif" WIDTH="3" HEIGHT="3"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="300" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR BGCOLOR="#FFFFFF"> 
    <TD BGCOLOR="#000000" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
    <TD VALIGN="TOP"> 
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0">
        <TR BGCOLOR="#000000"> 
          <TD><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
        </TR>
        <TR ALIGN="CENTER"> 
          <TD HEIGHT="30"><FONT COLOR="#000000">Ya Votaste Anteriormente</FONT></TD>
        </TR>
      </TABLE>
    </TD>
    <TD BGCOLOR="#000000" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
<TABLE WIDTH="300" BORDER="0" CELLSPACING="0" CELLPADDING="0">
  <TR> 
    <TD BACKGROUND="../img/general/fondo_ow.gif" WIDTH="100%"><IMG SRC="../img/general/form_left.gif" WIDTH="15" HEIGHT="15"></TD>
    <TD BGCOLOR="#000000" WIDTH="1"><IMG SRC="../img/general/spacer.gif" WIDTH="1" HEIGHT="1"></TD>
  </TR>
</TABLE>
</BODY>
</HTML>